version: '3.0'

services: 
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    expose:
      - 27017
  app:
    build:
      dockerfile: dockerfile
      context: back
    restart: always
